export { default as Behance } from './Behance.astro'
export { default as Github } from './Github.astro'
export { default as Instagram } from './Instagram.astro'
export { default as Linkedin } from './Linkedin.astro'
export { default as Moon } from './Moon.astro'
export { default as Sun } from './Sun.astro'
export { default as Twitter } from './Twitter.astro'
